server:
  port:
    9000
swagger:
  config:
    base-package: com.ss.controller
meta:
  chunk-size: 16000000
  chunk-instance-count: 1

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/meta